### PR TITLE
accept '_' and '-' in named parameters

### PR DESCRIPTION
**Pull request by rjourde**

### CODE REVIEW

**Comment by santiaago** [comment]
Looks good, can you add a test for this?

**Comment by rjourde** [comment]
yeah!

**Comment by rjourde** [comment]
Tests updated!

**Comment by santiaago** [comment]
Oh, I prefer to leave the tests as they are and add a new one that explicitly tests this:
Something like:
~~~go
func TestThatSpecialCharactersInParameterWork(t *testing.T) {
~~~

**Comment by rjourde** [comment]
Ok boy
Le lun. 26 janv. 2015 à 18:30, santiaago <notifications@github.com> a
écrit :

**Comment by rjourde** [comment]
New test case added!

**Pull request merged**
